=== vchychuzhko/alcotimer/app/code/Awesome/Framework/Schema/page_layout.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="page">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="head" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string" minOccurs="0"/>
                            <xs:element name="favicon" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="src" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="lib" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="src" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="script" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="src" type="xs:string" use="required"/>
                                    <xs:attribute name="async" type="xs:boolean" default="false"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="css" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="src" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="body" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="block" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element ref="referenceBlock" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element ref="container" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element ref="referenceContainer" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="block" type="blockType"/>
    <xs:element name="referenceBlock" type="referenceType"/>
    <xs:element name="container" type="containerType"/>
    <xs:element name="referenceContainer" type="referenceType"/>

    <xs:complexType name="blockType">
        <xs:sequence>
            <xs:element ref="block" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="referenceBlock" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="container" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="referenceContainer" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" use="required"/>
        <xs:attribute name="class" use="required"/>
        <xs:attribute name="template" use="required"/>
        <xs:attribute name="sortOrder"/>
    </xs:complexType>
    <xs:complexType name="containerType">
        <xs:sequence>
            <xs:element ref="block" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="referenceBlock" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="container" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="referenceContainer" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" use="required"/>
        <xs:attribute name="htmlTag"/>
        <xs:attribute name="htmlClass"/>
        <xs:attribute name="htmlId"/>
        <xs:attribute name="sortOrder"/>
    </xs:complexType>
    <xs:complexType name="referenceType">
        <xs:sequence>
            <xs:element ref="block" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="referenceBlock" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="container" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="referenceContainer" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" use="required"/>
        <xs:attribute name="remove"/>
        <xs:attribute name="sortOrder"/>
    </xs:complexType>
</xs:schema>

=== vchychuzhko/alcotimer/app/code/Vch/Timer/view/frontend/layout/timer_index_index.xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../../Frontend/Schema/page_layout.xsd">
    <head>
        <css src="Vch_Frontend/css/radial-slider.css"/>
        <css src="Vch_Frontend/css/range-slider.css"/>
        <css src="Vch_Timer/css/timer.css"/>
    </head>
    <body>
        <referenceBlock name="menu">
            <block name="timer.settings" class="Vch\Timer\Block\Timer" template="Vch_Timer::menu/settings.phtml"/>
        </referenceBlock>
        <referenceContainer name="page-wrapper">
            <block name="timer.content"
                   class="Vch\Timer\Block\Timer"
                   template="Vch_Timer::timer.phtml"
                   sortOrder="5"
            >
                <block name="timer.hint"
                       class="Vch\Frontend\Block\Template"
                       template="Vch_Timer::timer/hint.phtml"
                       ifConfig="timer/show_hint"/>
            </block>
        </referenceContainer>
    </body>
</page>

=== vchychuzhko/alcotimer/app/code/Awesome/Visualizer/view/frontend/layout/visualizer_index_index.xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../../Frontend/Schema/page_layout.xsd">
    <head>
        <title><![CDATA[Audio Spectrum]]></title>
        <description><![CDATA[Web app to visualize your music in real time.]]></description>
        <keywords translate="false"><![CDATA[AlcoTimer,Visualizer,Audio,Spectrum,Visualization,Visualize,Music,Podcast]]></keywords>
        <remove src="Awesome_Frontend/css/menu.css"/>
    </head>
    <body>
        <referenceBlock name="menu" remove="true"/>
        <referenceContainer name="page-wrapper">
            <referenceBlock name="header" remove="true"/>
            <referenceBlock name="menu-overlay" remove="true"/>
            <block name="visualizer.content"
                   class="Awesome\Visualizer\Block\Visualizer"
                   template="Awesome_Visualizer::visualizer.phtml"
                   sortOrder="5"/>
            <referenceBlock name="footer" remove="true"/>
        </referenceContainer>
        <referenceContainer name="popup-init-section" remove="true"/>
    </body>
</page>
